# Generated by Django 3.2 on 2025-09-10 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('items', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('itemName', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=100)),
                ('group_type', models.CharField(choices=[('Service', 'Service'), ('Product', 'Product'), ('Asset', 'Asset')], max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=50)),
                ('hsn', models.CharField(max_length=20)),
                ('stockReorderLevel', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='MessIntent',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('intent_number', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('items', models.JSONField(default=list)),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TravellerIntent',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('intent_number', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('items', models.JSONField(default=list)),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TravellersIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('grn_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_status', models.JSONField(blank=True, default=list, null=True)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_category', models.CharField(choices=[('TRAVELLERS IN CREDIT', 'TRAVELLERS IN CREDIT'), ('TRAVELLERS IN CASH', 'TRAVELLERS IN CASH')], max_length=50)),
                ('vendor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('credit_period', models.CharField(blank=True, max_length=50, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('CHEQUE', 'CHEQUE'), ('CASH', 'CASH'), ('CARD', 'CARD'), ('UPI', 'UPI')], max_length=50, null=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('non_taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('tax_paid_to_supplier', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('local_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('cgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('sgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('igst', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('cess', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('central_sales_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('round_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('tax_on_free_items', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('net_invoice_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('quotation_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('courier_transport_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
            ],
            options={
                'db_table': 'travellers_in',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('supplierType', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('addressLine1', models.CharField(max_length=255)),
                ('addressLine2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('contactPerson', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('kgstTinNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('gstin', models.CharField(max_length=15)),
                ('payment', models.CharField(blank=True, max_length=50, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
                ('creditPeriod', models.IntegerField(blank=True, null=True)),
                ('exportDataCode', models.CharField(blank=True, max_length=50, null=True)),
                ('tdsPercent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'vendors',
            },
        ),
    ]
