# Generated by Django 3.2 on 2025-09-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storetrustbackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contactPerson', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='items',
            options={},
        ),
        migrations.AddField(
            model_name='items',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='items',
            table=None,
        ),
    ]
