# Generated by Django 3.2 on 2026-07-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storetrustbackend', '0002_auto_20250924_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('outlet_code', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('item_id', models.IntegerField()),
                ('hsn', models.CharField(blank=True, max_length=50, null=True)),
                ('total_quantity', models.FloatField(default=0)),
                ('approved_quantity', models.FloatField(default=0)),
                ('opening_stock', models.FloatField(default=0)),
                ('grn_number', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'stock',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('outlet_name', models.CharField(max_length=255)),
                ('outlet_code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'db_table': 'store',
            },
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Items', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='vendors',
            options={'verbose_name': 'Vendors', 'verbose_name_plural': 'Vendors'},
        ),
        migrations.RemoveField(
            model_name='travellersin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='travellersin',
            name='total_amount_paid',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='creditPeriod',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='exportDataCode',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='tdsPercent',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='terms',
        ),
        migrations.AddField(
            model_name='items',
            name='item_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='items',
            name='openingStock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='outlet_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='messintent',
            name='outlet_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travellerintent',
            name='outlet_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travellersin',
            name='grn_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='travellersin',
            name='outlet_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendors',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendors',
            name='outlet_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='hsn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='travellersin',
            name='grn_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='travellersin',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='travellersin',
            name='purchase_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='gstin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='items',
            table='items',
        ),
    ]
